config/routes.rb
Rails.application.routes.draw do
  resources :details
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
    ransacker :t_schedule
    belongs_to :user
    has_many :categories, dependent: :destroy
    accepts_nested_attributes_for :categories, reject_if: :all_blank, allow_destroy: true
    has_many :m_features, dependent: :destroy
    accepts_nested_attributes_for :m_features, reject_if: :all_blank, allow_destroy: true
    has_many :details
    has_many :orders, through: :details, dependent: :destroy
    has_many_attached :images

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @q=Product.ransack(params[:q])
    @products=@q.result(distinct:true).page(params[:page]).per(20)
  end
  

  # GET /products/1 or /products/1.json
  def show
    authorize! :read, @product
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.categories.build
    @product.m_features.build

    
  end

  # GET /products/1/edit
  def edit
    @product.categories.build
    @product.m_features.build
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :desciption, :price, :cost, :t_schedule, :stock, :img_url, :user_id,images:[], categories_attributes: [:id, :name, :description, :product_id, :_destroy], m_features_attributes: [:id, :name, :description, :product_id, :_destroy])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_category_fields.html.erb
<div class="nested-fields">
      <%= f.label :name, value:"Nombre Categoria", style: "display: block" %>
      <%= f.text_field :name %>
      <%= link_to_remove_association "Eliminar categoria", f %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <div>
      <%= form.hidden_field :user_id, value: current_user.id%>
    </div>
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>

    <div>
      <%= form.label :desciption, style: "display: block" %>
      <%= form.text_area :desciption %>
    </div>

    <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.number_field :price %>
    </div>

    <div>
      <%= form.label :cost, style: "display: block" %>
      <%= form.number_field :cost %>
    </div>

    <div>
      <%= form.label :t_schedule, style: "display: block" %>
      <%= form.number_field :t_schedule %>
    </div>

    <div>
      <%= form.label :stock, style: "display: block" %>
      <%= form.number_field :stock %>
    </div>

    <div>
      <%= form.label :img_url, style: "display: block" %>
      <%= form.text_field :img_url %>
    </div>
    <div>
      <legend>Categoria:</legend>
      <%= form.fields_for :categories do |ff| %>
        <%= render "category_fields", :f => ff %>
      <%end%>
    </div>
    <div>
      <%= link_to_add_association 'Añadir categorias', form, :categories %>
    </div>
    <div>
      <legend>Caracteristica:</legend>
      <%= form.fields_for :m_features do |ff| %>
        <%= render "m_feature_fields", :f => ff %>
      <%end%>
    </div>
    <div>
      <%= link_to_add_association 'Añadir caracteristicas', form, :m_features %>
    </div>
    <div class="field">
      <%= form.label :images %>
      <%= form.file_field :images,multiple: true %>
    </div>

    <div>
      <%= form.submit "enviar" , class:"btn btn-boz"%>
    </div>
  </div>
<% end %>

app/views/products/_m_feature_fields.html.erb
<div class="nested-fields">

      <%= f.label :name, value:"Caracteristica", style: "display: block" %>
      <%= f.text_field :name %>
      <%= link_to_remove_association "Eliminar caracteristica", f %>

</div>

app/views/products/_product.html.erb
<div  id="<%= dom_id product %>" >
  <div>
    <%=image_tag product.img_url, class:"sz"%>
  </div>
  <br>
  <div>
    <%if product.images.count>0%>
      <%product.images.each do |image|%>
        <%= image_tag image, size: "50"%>
      <%end%>
    <%end%>
  </div>
  <div class="card-body">
  <p>
    <strong>Nombre:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= product.desciption %>
  </p>

  <p>
    <strong>Precio:</strong>
      <%= number_to_currency(product.price, unit: "$ ", separator: ",", delimiter: ".", format: " %u %n") %>
  </p>

  <p>
    <strong>Costo:</strong>
    <%= number_to_currency(product.cost, unit: "$ ", separator: ",", delimiter: ".", format: " %u %n") %>
  </p>

  <p>
    <strong>Agenda: </strong><%= product.t_schedule %> Dias 
  </p>
  <p>
    <strong>Stock: </strong><%= product.stock %> Unidad(es)   
     </p>
    <%if product.categories.count>0%>
    <p>
    <strong>Categoria: </strong>
      <%product.categories.each do |c|%>
        <li class="mx-5"><%=c.name%></li>
      <%end%>
    </p>  
  <%end%>
  <%if product.m_features.count>0%>
    <p>
    <strong>Caracteristica: </strong>
      <%product.m_features.each do |c|%>
        <li class="mx-5"><%=c.name%></li>
      <%end%>
    </p>
  <%end%>  
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product, class: "lk-boz" %> |
  <%= link_to "Back to products", products_path,class: "lk-boz" %>
</div>

app/views/products/index.html.erb
<h1>Productos</h1>
<br>
 
<div class="row">
    <div class="col-7">

        <%if current_user.role=="seller"%>
               
                <%= link_to "New product", new_product_path, class:"btn btn-boz  justify-content-start col-2 "%>
        
        <%end%>
    </div>
    <div class="col-5 d-flex justify-content-end ">

       

            <%= search_form_for @q do |f|%>
                <%= f.label :t_schedule%>
                <%= f.search_field :t_schedule_eq%>
                <%= f.submit "Buscar", class:"btn btn-boz"%>
            <%end%>
    </div>
</div>

    <nav class="navbar text-white justify-content-center lk-boz">
            <%= paginate @products%>
    </nav>


    <table class="table table-striped table-bordered table-hover lk-boz">
            <thead>
                <tr th class="align-middle text-center text-decoration-none"> 
                    <th scope="col"> Producto</th>
                    <th scope="col"> <%= sort_link(@q, :name, "Nombre") %></th>
                    <th scope="col"> Descripcion </th>
                    <th scope="col"> Costo Producto</th>
                    <th scope="col"> Precio Venta Prod </th>
                    <th scope="col"> Stock Cant</th>
                    <th scope="col"> Dias Agend </th>
                    
                </tr>
            </thead>

            <tbody class="text-decoration-none" >
                <% @products.each do |prod| %>
                    <tr>    
                        <td class="align-middle text-center" >
                            <%= image_tag(prod.img_url, size: "60x60") %>    
                        </td>
                        <td class="align-middle text-center">
                            <h6><strong><%= prod.name %><h6>
                        </td>
                        <td class="align-middle ">
                            <%= prod.desciption %>
                        </td>
                        <td class="align-middle text-center">
                            <%= number_to_currency(prod.cost, unit: "$ ", precision: 0, separator: ",", delimiter: ".", format: " %u %n") %>
                        </td>
                        <td class="align-middle text-center">
                            <%= number_to_currency(prod.price, unit: "$ ", precision: 0, separator: ",", delimiter: ".", format: " %u %n") %>
                        </td>
                        
                       <td class="align-middle text-center">
                            <%= prod.stock %>
                        </td>
                        <td class="align-middle text-center">
                            <%= prod.t_schedule %>
                        </td>

                        <td class="align-middle text-center">
                          <%= link_to "Mostrar", prod, class: "lk-boz" %>
                        </td> 
                        <% if can? :update, prod %>
                        <td class="align-middle text-center">
                            <%if prod.user_id==current_user.id%>
                                <%= link_to "Editar", edit_product_path(prod), class:"lk-boz" %> 
                            <%end%>
                        </td>
                        


                        <td class="align-middle">
                            <%if prod.user_id==current_user.id%>
                                <!-- Protección CSRF -->
                                <%= token_tag nil %> 
    
                                <%= button_to "Eliminar", product_path(prod), method: :delete, class: "btn btn-boz btn-sm", data: { confirm: "Are you sure?" }, :html => { :method => :delete, :remote => true}, onclick: "return confirmDestroy('Seguro que desea eliminar el Producto seleccionado?')"%>
                            <%end%>
                            </td>
                        <%end%> 
                    </tr>
                    <% end %>
            </tbody>
    </table>

    <nav class="navbar text-white justify-content-center">
            <%= paginate @products %>
    </nav>





<script>
function confirmDestroy(message) {
  if (!confirm(message)) {
    return false;
  }
}
</script>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path,class:"lk-boz" %>
</div>

app/views/products/show.html.erb
<h1>Mostrar</h1>
<%= render @product %>
<div>
  <%if @product.user_id==current_user.id%>
    <%= link_to "Edit this product", edit_product_path(@product),class:"lk-boz" %> |
  <%end%>  
  <%= link_to "Back to products", products_path,class:"lk-boz" %>
  <%if @product.user_id==current_user.id%>
    <%= button_to "Destroy this product", @product, method: :delete,class:"btn btn-boz" %>
  <%end%>
</div>