config/routes.rb
Rails.application.routes.draw do
  resources :details
  resources :orders
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "products#index"
end

app/models/detail.rb
class Detail < ApplicationRecord
    belongs_to :product
    belongs_to :order
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  before_action :set_detail, only: %i[ show edit update destroy ]

  # GET /details or /details.json
  def index
    @details = Detail.all

  end

  # GET /details/1 or /details/1.json
  def show
  end

  # GET /details/new
  def new
    @detail = Detail.new
    @products=Product.all
    @orders=Order.all
  end

  # GET /details/1/edit
  def edit
    @products=Product.all
    @orders=Order.all
  end

  # POST /details or /details.json
  def create
    @products=Product.all
    @orders=Order.all
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to detail_url(@detail), notice: "Detail was successfully created." }
        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1 or /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to detail_url(@detail), notice: "Detail was successfully updated." }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1 or /details/1.json
  def destroy
    @detail.destroy

    respond_to do |format|
      format.html { redirect_to details_url, notice: "Detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detail
      @detail = Detail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def detail_params
      params.require(:detail).permit(:quanty, :unit_price, :order_id,:product_id)
    end
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/views/details/_detail.html.erb
<div id="<%= dom_id detail %>">
  <p>
    <strong>product:</strong>
    <%= detail.product.name %>
  </p>
  <p>
    <strong>order:</strong>
    <%= detail.order.num_order %>
  </p>
  <p>
    <strong>Quanty:</strong>
    <%= detail.quanty %>
  </p>

  <p>
    <strong>Unit price:</strong>
    <%= detail.unit_price %>
  </p>

</div>

app/views/details/_form.html.erb
<%= form_with(model: detail) do |form| %>
  <% if detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(detail.errors.count, "error") %> prohibited this detail from being saved:</h2>

      <ul>
        <% detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :product, style: "display: block" %>
    <%= form.collection_select :product_id, @products, :id, :name %>
  </div>
  <div>
    <%= form.label :order, style: "display: block" %>
    <%= form.collection_select :order_id, @orders, :id,:num_order %>
  </div>

  <div>
    <%= form.label :quanty, style: "display: block" %>
    <%= form.number_field :quanty %>
  </div>

  <div>
    <%= form.label :unit_price, style: "display: block" %>
    <%= form.number_field :unit_price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/details/edit.html.erb
<h1>Editing detail</h1>

<%= render "form", detail: @detail %>

<br>

<div>
  <%= link_to "Show this detail", @detail %> |
  <%= link_to "Back to details", details_path %>
</div>

app/views/details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Details</h1>

<div id="details">
  <% @details.each do |detail| %>
    <%= render detail %>
    <p>
      <%= link_to "Show this detail", detail %>
    </p>
  <% end %>
</div>

<%= link_to "New detail", new_detail_path %>

app/views/details/new.html.erb
<h1>New detail</h1>

<%= render "form", detail: @detail %>

<br>

<div>
  <%= link_to "Back to details", details_path %>
</div>

app/views/details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @detail %>

<div>
  <%= link_to "Edit this detail", edit_detail_path(@detail) %> |
  <%= link_to "Back to details", details_path %>

  <%= button_to "Destroy this detail", @detail, method: :delete %>
</div>